
<ul class="form-group">
    <li>
        <label for="categoryOfResID">Danh mục nhà hàng</label>
        <select id="categoryOfResID" name="categoryOfResID">
          <option id="" value="" selected="selected">--Chọn loại nhà hàng--</option>
          <?php foreach($categories as $item){?>
             <option id="<?php echo $item->categoryOfResID; ?>" value="<?php echo $item->categoryOfResID; ?>" <?php if(isset($categoryOfResID) && $categoryOfResID == $item->categoryOfResID){ echo 'selected="selected"';} else {echo '';} ?> >
             <?php echo $item->nameCOR; ?>
             </option>
          <?php } ?>
        </select>
    </li>
    <li>
        <input type="hidden" id="restaurantID" name="restaurantID" value="<?php echo isset($restaurantID) ? $restaurantID : '0'; ?>">
        <input type="hidden" id="userID" name="userID" value="<?php echo isset($userID) ? $userID : '0'; ?>">
        <label for="memName">Tên nhà hàng</label>
        <input type="text" value="<?php echo isset($nameRe) ? $nameRe : ''; ?>" id="nameRe"  name="nameRe">
    </li>
    <li>
        <label for="userName">Điện thoại</label>
        <input type="text" id="phoneRe"  name="phoneRe"  value="<?php echo isset($phoneRe) ? $phoneRe : ''; ?>">
    </li>
    <li>
    <label for="favouriteFood">Món ăn nổi bật</label>
    <input type="text" id="favouriteFood"  name="favouriteFood"  value="<?php echo isset($favouriteFood) ? $favouriteFood : ''; ?>">
    </li>
    <li>
        <label for="spaceRes">Không gian nhà hàng</label>
        <input type="text" id="spaceRes"  name="spaceRes"  value="<?php echo isset($spaceRes) ? $spaceRes : ''; ?>">
    </li>
    <li>
        <label for="carParkingRes">Chỗ đỗ xe</label>
        <input type="text" id="carParkingRes"  name="carParkingRes"  value="<?php echo isset($carParkingRes) ? $carParkingRes : ''; ?>">
    </li>
    <li>
        <label for="openTimeRe">Giờ mở cửa</label>
        <div class='R-time'>
            <input placeholder="Mở cửa" class="textbox-n" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" id="openTimeRe" name="openTimeRe" value="<?php echo isset($openTimeRe) ? $openTimeRe : ''; ?>">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
        </div>
        -
        <div class='R-time'>
            <input placeholder="Mở cửa" class="textbox-n" type="text" onfocus="(this.type='time')" onblur="(this.type='text')" id="closeTimeRe" name="closeTimeRe" value="<?php echo isset($closeTimeRe) ? $closeTimeRe : ''; ?>">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
        </div>
    </li>
<!--    <div class="col-lg-4">-->
<!--        <label for="closeTimeRe">Giờ đóng cửa</label>-->
<!--        <div class='R-time' style="position: relative">-->
<!--            <input type="text" class="form-control" id="closeTimeRe"  name="closeTimeRe"  value="--><?php //echo isset($closeTimeRe) ? $closeTimeRe : ''; ?><!--">-->
<!--            <span class="input-group-addon">-->
<!--                <span class="glyphicon glyphicon-calendar"></span>-->
<!--            </span>-->
<!--        </div>-->
<!--    </div>-->


    <li>
        <label for="rateRe">rateRe</label>
        <select disabled="disabled" id="rateRe" name="rateRe">
            <option id="0" value="0" <?php if(isset($rateRe) && $rateRe == 0){ echo 'selected="selected"';} else {echo '';} ?> >0 *</option>
            <option id="1" value="1" <?php if(isset($rateRe) && $rateRe == 1){ echo 'selected="selected"';} else {echo '';} ?> >1 *</option>
            <option id="2" value="2" <?php if(isset($rateRe) && $rateRe == 2){ echo 'selected="selected"'; } else {echo '';} ?>>2 *</option>
            <option id="3" value="3" <?php if(isset($rateRe) && $rateRe == 3){ echo 'selected="selected"'; } else {echo '';} ?>>3 *</option>
            <option id="4" value="4" <?php if(isset($rateRe) && $rateRe == 4){ echo 'selected="selected"'; } else {echo '';} ?>>4 *</option>
            <option id="5" value="5" <?php if(isset($rateRe) && $rateRe == 5){ echo 'selected="selected"'; } else {echo '';} ?>>5 *</option>
        </select>
    </li>
    <li>
        <label></label>
        <span class="edit-checkbox">
            <input type="checkbox" name="isDepositBo" id="isDepositBo" <?php echo (isset($isDepositBo) && $isDepositBo) ? 'checked': ''; ?>> Cọc tiền trước
        </span>
        <span class="edit-checkbox">
            <input type="checkbox" namename="isDeactivate" id="isDeactivate" <?php echo (isset($isDeactivate) && $isDeactivate) ? 'checked': ''; ?>> Dừng hoạt động
        </span>
        <span class="edit-checkbox">
            <input type="checkbox" disabled="disabled" namename="statusRes" id="statusRes" <?php echo (isset($statusRes) && $statusRes) ? 'checked': ''; ?>> Trạng thái
        </span>
</ul>
<script type="">
    $('.datepicker').datetimepicker({locale: 'vi'});
    $('.time').datetimepicker({locale: 'vi',format: 'hh:mm'});
    $(document).ready(function(){
        var ok = '<?php echo isset($ok) ? $ok : ''; ?>';
        if (ok == '1')
        {
            setTimeout(function(){
                location.href = '<?php echo base_url().'user_profile/restaurant_edit'; ?>';    
            }, 2000)                                                                       
        }
    })
</script>