
<ul>
    <li>
        <label for="minPrice">Giá tiền (thấp - cao: vnđ)</label>
        <input style="width: 24.3%" type="number" id="minPrice"  name="minPrice"  value="<?php echo isset($minPrice) ? $minPrice : ''; ?>"> -
        <input style="width: 24.3%" type="number" id="maxPrice"  name="maxPrice"  value="<?php echo isset($maxPrice) ? $maxPrice : ''; ?>">
    </li>
    <li>
        <label for="discount">Giảm giá (%)</label>
        <input type="number" id="discount"  name="discount"  value="<?php echo isset($discount) ? $discount : ''; ?>">
    </li>
   </ul>